# Generated by Django 5.2.8 on 2025-11-14 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AVION', 'Avión'), ('HELICOPTERO', 'Helicóptero')], max_length=20)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('capacidad_kg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('licencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('certificacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('tipo_transporte', models.CharField(choices=[('TERRESTRE', 'Terrestre'), ('AEREA', 'Aérea')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAMION', 'Camión'), ('FURGON', 'Furgón'), ('BUS', 'Bus')], max_length=20)),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('capacidad_kg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('peso_kg', models.FloatField()),
                ('valor', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20)),
                ('aeronave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.aeronave')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.carga')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.conductor')),
                ('piloto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.piloto')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.ruta')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporte.vehiculo')),
            ],
        ),
    ]
