# Generated by Django 5.2.8 on 2025-11-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_aeronave_activo_conductor_activo_piloto_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='rut',
            field=models.CharField(default=21844914, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
