# Generated by Django 5.2.8 on 2025-11-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_conductor_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='piloto',
            name='rut',
            field=models.CharField(default=21844913, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
